POST http://localhost:8080/member
content-type: application/json

{
  "loginId": "jahni",
  "password": "1234"
}

###
POST http://localhost:8080/member/login
content-type: application/json

{
  "loginId": "jahni",
  "password": "1234"
}

###
GET http://localhost:8080/meber/1

